Rename method do avoid conflicts with Rails
ActiveRecord::Base already defines a `changed?` method with a
different arity.

http://edgeapi.rubyonrails.org/classes/ActiveModel/Dirty.html#method-i-changed-3F

Reusing the same name for a different method causes an error
while running tests on Audits:

ArgumentError: expected 0 arguments, received 1.